/* eslint-disable import/no-unassigned-import */
/* eslint-disable canonical/filename-match-exported */
import './globals.css';
import { type Metadata } from 'next';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({ children }: { readonly children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
